apiVersion: v2
name: ilf-wallet-backend
description: Interledger App Wallet backend service for the Interledger App network
home: https://github.com/interledger/interledger-app

type: application
version: 0.4.2
appVersion: "v0.1.2"

dependencies:
  - name: common
    version: 0.3.0
    repository: https://interledger.github.io/charts/interledger

maintainers:
  - name: Stephan Butler
    email: stephan@interledger.foundation
