apiVersion: v2
name: ilf-wallet-backend
description: Interledger App Wallet backend service for the Interledger App network
home: https://github.com/interledger/interledger-app

type: application
version: 2.3.3
appVersion: v1.2.30

dependencies:
  - name: common
    version: 0.9.0
    repository: https://interledger.github.io/charts/interledger

maintainers:
  - name: Stephan Butler
    email: stephan@interledger.foundation
  - name: Radu Popa
    email: radu@interledger.foundation
