apiVersion: v2
name: ilf-wallet-backend
description: Interledger App Wallet backend service for the Interledger App network
home: https://github.com/interledger/interledger-app

type: application
version: 0.5.1
appVersion: "manual_main"

dependencies:
  - name: common
    version: 0.3.4
    repository: https://interledger.github.io/charts/interledger

maintainers:
  - name: Stephan Butler
    email: stephan@interledger.foundation
