apiVersion: v2
name: web-monetization-tools
description: Web Monetization Tools Helm chart for Kubernetes
home: https://github.com/interledger/testnet

type: application
version: 1.1.0
appVersion: "v0.0.19"

icon: https://interledger.github.io/charts/icons/wm_logo.png

dependencies:
  - name: common
    version: 0.8.0
    repository: https://interledger.github.io/charts/interledger

maintainers:
  - name: Stephan Butler
    email: stephan@interledger.foundation
