apiVersion: v2
name: common
description: ILF common helm chart for building k8s resources

type: library
version: 0.4.1

maintainers:
  - name: golobitch
    email: tadej.golobic@gatehub.net
  - name: Stephan butler
    email: stephan@interledger.foundation
