apiVersion: v2
name: wallet-backend
description: Rafiki Money Backend Helm chart for Kubernetes
home: https://github.com/interledger/testnet

type: application
version: 0.0.25
appVersion: "v0.1.33"

dependencies:
  - name: common
    version: 0.1.0
    repository: file://../../common

maintainers:
  - name: golobitch
    email: tadej.golobic@gatehub.net
