nodeEnv: production
logLevel: info

replicaCount: 1

nodeSelector: {}

serviceAccount:
  create: false
  annotations: {}
  name: ""

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 1
  cpuUtilizationPercentage: 80
  memoryUtilizationPercentage: 80

service:
  - name: service
    type: ClusterIP
    ports:
      - port: 4003
        targetPort: 4003
        protocol: TCP
        name: http

containers:
  - name: server
    image:
      name: test-wallet-backend
    envFrom:
      - configMapRef:
          name: "{{ .Release.Name }}"
      - secretRef:
          name: "{{ .Release.Name }}"
    resources:
      requests:
        memory: 256Mi
        cpu: 1
      limits:
        memory: 2048Mi
        cpu: 4
    ports:
      - name: http
        containerPort: 4003
        protocol: TCP

ingress:
  enabled: true
  className: nginx
  tls:
    - secretName: interledger-test-dev-tls
      hosts:
        - wallet.interledger-test.dev
  hosts:
    - host: wallet.interledger-test.dev
      paths:
        - path: /
          pathType: Prefix
          service:
            name: rafiki-money-frontend-service
            port: 4003

configmap:
  - files/config.yaml
secret:
  - files/secret.yaml

port: 4003
paymentPointer:
database:
  url: postgres://test:test@postgres-test-postgresql/test
cookie:
  name: testnet.cookie
  password: testnet.cookie.password.super.secret.ilp
  ttl: 2630000
identity:
  serverSecret: 58ba1bdc-e625-42da-bc90-bcea29b4ab8b
webhook:
  signatureSecret: A3F44B29-56B2-4C7F-ACA7-1A111C4A6B05 # TODO: replace this
redis:
  url: redis://redis-test.interledger-test:6379
gatehub:
  env: sandbox
  accessKey:
  secretKey: aergaregaerg # TODO: replace this
  gatewayUuid: 9358542e-9bd1-48bc-b869-8661f1a1827c
  webhookSecret: aergaerg # TODO: replace this
  settlementWalletAddress:
  cards:
    appId: 713d6b92-afce-4797-8100-43877167784b
    accountProductCode: PWSR_DEBP_2404
    productCode: PMDSGWEEA
    nameOnCards: INTERLEDGER
    paymentPointerPrefix: ilp.dev
  vault:
    eur: a09a0a2c-1a3a-44c5-a1b9-603a6eea9341
    usd: 450d2156-132a-4d3f-88c5-74822547658d
email:
  send: true
  from: tech@interledger.org
  sendgridKey: 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
interaction:
  cookieSameSite:
hosts:
  openPayments: https://ilp.interledger-test.dev
  graphqlEndpoint: http://rafiki-backend-test.interledger-test:3001/graphql
  authGraphqlEndpoint: http://rafiki-auth-test-service.interledger-test:3003/graphql
  frontend: https://wallet.interledger-test.dev
  auth: http://rafiki-auth-test-service.interledger-test:3009
rate:
  apiKey: fca_live_Q4pfUGScjJed6zPS7JNGHipXg1jjAZZrKVIPcx3J
card:
  pinUrl: https://lab.dinitcs.com/uat/Stargate.Paywiser.Server/api/v3/ClientDevice/pin
  dataUrl: https://lab.dinitcs.com/uat/Stargate.Paywiser.Server/api/v3/ClientDevice/cardData
