{{- include "common.secret" (list . "web-monetization-tools-backend.secret") }}

{{- define "web-monetization-tools-backend.secret" -}}
{{- $top := first . }}
data:
  {{- range $top.Values.secret }}
    {{- tpl ($top.Files.Get .) $top | nindent 6 -}}
  {{- end }}
{{- end }}
