apiVersion: v2
name: interledger-pay
description: Interledger Pay
home: https://github.com/interledger/interledger-pay

type: application
version: 0.2.3
appVersion: "v1.1.15"

dependencies:
  - name: common
    version: 0.8.1
    repository: https://interledger.github.io/charts/interledger

maintainers:
  - name: Stephan Butler
    email: stephan@interledger.foundation
