TEMPORAL_GRPC_ENDPOINT: "{{ .Release.Name }}-temporal:7233"
TEMPORAL_PERMIT_WRITE_API: "true"
TEMPORAL_UI_PORT: "8080"

VITE_TEMPORAL_PORT: "7233"
VITE_API: "http://{{ .Release.Name }}-temporal:8233"
