{{- define "rafiki-money.backend.SecretsMap" -}}
{{- end }}
{{- if .Values.config.backend.shouldCreateSecrets }}
{{- include "common.secretMapper" (list . .Values.secretsMaps.backend "rafiki-money.backend.SecretsMap") }}
{{- end }}
