DATABASE_URL: {{ (printf "postgresql://%s:%s@%s:%s/%s" .Values.postgresql.auth.username .Values.postgresql.auth.password .Values.postgresql.host .Values.postgresql.port .Values.postgresql.auth.database) | b64enc | quote }}
REDIS_URL: {{ (printf "redis://%s:%s" .Values.redis.host .Values.redis.port) | b64enc | quote }}
AUTH_IDENTITY_SERVER_SECRET: "{{ .Values.authIdentityServerSecret }}"
JOPACC_BASIC_AUTH: "{{ .Values.jopaccBasicAuth }}"
