{{- define "rafiki.backend.ConfigMap" -}}
{{- $top := first . }}
data:
    WALLET_ADDRESS_URL: "{{ $top.Values.config.backend.ilp.host }}/.well-known/pay"
{{- end }}
{{- if .Values.deployments.backend.enabled }}
{{- include "common.configMapper" (list . .Values.configMaps.backend "rafiki.backend.ConfigMap") }}
{{- end }}
