{{- define "rafiki.auth.SecretsMap" -}}
{{- end }}
{{- if and .Values.deployments.auth.enabled .Values.config.auth.shouldCreateSecrets }}
{{- include "common.secretMapper" (list . .Values.secretsMaps.auth "rafiki.auth.SecretsMap") }}
{{- end }}
