{{- define "interledger-app-backend.deployment.server" -}}
{{- $top := first . -}}
metadata:
    name: {{ include "common.fullname" $top }}-server
    labels:
        app.kubernetes.io/instance: {{ include "common.fullname" $top }}
        app.kubernetes.io/name: {{ include "common.fullname" $top }}-server
spec:
    selector:
        matchLabels:
            app.kubernetes.io/instance: {{ include "common.fullname" $top }}
            app.kubernetes.io/name: {{ include "common.fullname" $top }}-server
    template:
        metadata:
            labels:
                app.kubernetes.io/instance: {{ include "common.fullname" $top }}
                app.kubernetes.io/name: {{ include "common.fullname" $top }}-server
        spec:
            topologySpreadConstraints:
                -   maxSkew: 1
                    topologyKey: kubernetes.io/hostname
                    whenUnsatisfiable: DoNotSchedule
                    labelSelector:
                        matchLabels:
                            app.kubernetes.io/instance: {{ include "common.fullname" $top }}
                            app.kubernetes.io/name: {{ include "common.fullname" $top }}-server
        
{{- end }}
{{- include "common.deployment" (list . .Values.server .Values.server.autoscaling .Values.server.serviceAccount "interledger-app-backend.deployment.server") }}
