{{- define "server.deployment" -}}
{{- $top := first . }}
{{- $cfgObj := include "common.configMapper" (list $top $top.Values.configMaps.config "interledger-app.ConfigMap") | fromYaml -}}
{{- $dataHash := $cfgObj.data | toJson | sha256sum -}}
spec:
  template:
    metadata:
      annotations:
        ilf-configmap-worker-sha256: {{ $dataHash | quote }}
{{- end }}
{{- if .Values.server.enabled }}
{{- include "common.deployment" (list . .Values.server .Values.server.autoscaling .Values.server.serviceAccount "server.deployment") }}
{{- end }}
