{{- define "interledger-app-backend.deployment.server" -}}
{{- $top := first . -}}
{{- $deployment := index . 1 -}}
{{- $name := printf "%s-%s" (include "common.fullname" $top) "server" -}}
metadata:
    name: {{ include "common.fullname" $top }}-server
    labels:
        app.kubernetes.io/instance: {{ include "common.fullname" $top }}
        app.kubernetes.io/name: {{ $name }}
spec:
    selector:
        matchLabels:
            app.kubernetes.io/instance: {{ include "common.fullname" $top }}
        app.kubernetes.io/name: {{ $name }}
    template:
        metadata:
            labels:
                app.kubernetes.io/instance: {{ include "common.fullname" $top }}
                app.kubernetes.io/name: {{ $name }}
        spec:
            topologySpreadConstraints:
                -   maxSkew: 1
                    topologyKey: kubernetes.io/hostname
                    whenUnsatisfiable: DoNotSchedule
                    labelSelector:
                        matchLabels:
                            app.kubernetes.io/instance: {{ include "common.fullname" $top }}
                            app.kubernetes.io/name: {{ $name }}
        
{{- end }}
{{- include "common.deployment" (list . .Values.server .Values.server.autoscaling .Values.server.serviceAccount "interledger-app-backend.deployment.server") }}
