{{- define "interledger-app-backend.deployment.server" -}}
{{- $top := first . -}}
metadata:
    name: {{ include "common.fullname" $top }}-server
spec:
    selector:
        matchLabels:
            app.kubernetes.io/instance: wallet-backend-server
            app.kubernetes.io/name: wallet-backend-server
    template:
        metadata:
            labels:
                app.kubernetes.io/instance: wallet-backend-server
                app.kubernetes.io/name: wallet-backend-server
{{- end }}
{{- include "common.deployment" (list . .Values.server .Values.server.autoscaling .Values.server.serviceAccount "interledger-app-backend.deployment.server") }}
