{{- define "interledger-app-backend.pdb.worker" -}}
{{- $top := first . -}}
{{- $deployment := index . 1 -}}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "common.fullname" $top }}-worker
  labels:
    app.kubernetes.io/name: {{ include "common.fullname" $top }}-worker
    app.kubernetes.io/instance: {{ include "common.fullname" $top }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "common.fullname" $top }}-worker
      app.kubernetes.io/instance: {{ include "common.fullname" $top }}
  minAvailable: 1
{{- end }}
{{- include "interledger-app-backend.pdb.worker" (list . .Values.worker) }}
