{{- if .Values.secrets.create -}}
# {{- required "Error: .Values.redisUri.value must be set" .Values.redisUri.value }}    
# {{- required "Error: .Values.databaseUri.value must be set" .Values.databaseUri.value }}
# {{- required "Error: .Values.quoteSignatureSecret.value must be set" .Values.quoteSignatureSecret.value }}
# {{- required "Error: .Values.ilp.streamSecret.value must be set" .Values.ilp.streamSecret.value }}
{{- end -}}