{{- define "interledger-app-frontend.configMap" -}}
{{- $top := first . }}
data:
  {{- range $top.Values.configmap }}
    {{- tpl ($top.Files.Get .) $top | nindent 6 -}}
  {{- end }}
{{- end }}

{{- include "common.configMap" (list . "interledger-app-frontend.configMap") }}
