{{- define "server.deployment" -}}
{{- $top := first . }}
{{- if $top.Values.server.enabled }}
{{- $cfgObj := include "common.configMapper" (list $top $top.Values.configMaps.server) | fromYaml -}}
{{- $dataHash := $cfgObj.data | toJson | sha256sum -}}
spec:
  template:
    metadata:
      annotations:
        ilf-configmap-server-sha256: {{ $dataHash | quote }}
{{- end }}
{{- end }}
{{- include "common.deployment" (list . .Values.server .Values.server.autoscaling .Values.server.serviceAccount "server.deployment") }}
