{{- include "common.secret" (list . "interledger-app-frontend.secret") }}
{{- define "interledger-app-frontend.secret" -}}
{{- $top := first . }}
metadata:
  name: {{ $top.Release.Name }}
data:
  {{- range $top.Values.secrets }}
    {{- tpl ($top.Files.Get .) $top | nindent 6 -}}
  {{- end }}
{{- end }}