apiVersion: v2
name: ilf-wallet-admin
description: Interledger App Wallet admin service for the Interledger App network
home: https://github.com/interledger/interledger-app

type: application
version: 0.3.2
appVersion: "v0.2.2"

dependencies:
  - name: common
    version: 0.3.4
    repository: https://interledger.github.io/charts/interledger

maintainers:
  - name: Stephan Butler
    email: stephan@interledger.foundation
