apiVersion: v2
name: ilf-wallet-admin
description: Interledger App Wallet admin service for the Interledger App network
home: https://github.com/interledger/interledger-app

type: application
version: 0.1.1
appVersion: "v0.1.0"

dependencies:
  - name: common
    version: 0.2.1
    repository: https://interledger.github.io/charts/interledger

maintainers:
  - name: Stephan Butler
    email: stephan@interledger.foundation
