apiVersion: v2
name: ilf-wallet-admin
description: Interledger App Wallet admin service for the Interledger App network
home: https://github.com/interledger/interledger-app

type: application
version: 1.1.5
appVersion: "v1.1.4"

dependencies:
  - name: common
    version: 0.4.2
    repository: https://interledger.github.io/charts/interledger

maintainers:
  - name: Stephan Butler
    email: stephan@interledger.foundation
