apiVersion: v2
name: ilf-wallet-admin
description: Interledger App Wallet admin service for the Interledger App network
home: https://github.com/interledger/interledger-app

type: application
version: 2.1.0
appVersion: v1.2.16

dependencies:
  - name: common
    version: 0.7.0
    repository: https://interledger.github.io/charts/interledger

maintainers:
  - name: Stephan Butler
    email: stephan@interledger.foundation
