COOKIE_SECRETS: "{{ required "needs config.cookie_secrets" .Values.config.cookie_secrets | b64enc }}"
DATO_API_TOKEN: "{{ required "needs config.dato_api_token" .Values.config.dato_api_token | b64enc }}"
BT_TOKEN: "{{ required "needs config.bt_token" .Values.config.bt_token | b64enc }}"
SENTRY_DSN: "{{ required "needs config.sentry_dsn" .Values.config.sentry_dsn | b64enc }}"
SEGMENT_API_KEY: "{{ required "needs config.segment_api_key" .Values.config.segment_api_key | b64enc }}"
CF_TURNSTILE_SITE_KEY: "{{ required "needs config.cf_turnstile_site_key" .Values.config.cf_turnstile_site_key | b64enc }}"
CF_TURNSTILE_SECRET_KEY: "{{ required "needs config.cf_turnstile_secret_key" .Values.config.cf_turnstile_secret_key | b64enc }}"
RAFIKI_AUTH_SECRET: "{{ required "needs config.rafiki.auth.secret" .Values.config.rafiki.auth.secret | b64enc }}"
REDIS_URL: "{{ required "needs config.redis.url" .Values.config.redis.url | b64enc }}"