{{- define "common.secret.tpl" -}}
{{- $top := first . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" $top }}
  {{- include "common.metadata"  (list $top) | nindent 2 }}
type: {{ $top.Values.secretType | default "Opaque" }}
data: {}
{{- end }}

{{- define "common.secret" -}}
{{- include "common.utils.merge" (append . "common.secret.tpl") }}
{{- end }}
