apiVersion: v2
name: rafiki
description: Rafiki Helm chart for Kubernetes
home: https://github.com/interledger/rafiki

type: application
version: 1.1.0
appVersion: "v1.2.1-beta"

dependencies:
  - name: common
    version: 0.9.0
    repository: https://interledger.github.io/charts/interledger

maintainers:
  - name: Stephan Butler
    email: stephan@interledger.foundation
