FYNBOS_ENV: "{{ .Values.config.environment }}"
KRATOS_URL: "{{ .Values.config.kratos.url }}"
KRATOS_ADMIN_URL: "{{ .Values.config.kratos.admin_url }}"
LOG_LEVEL: "{{ .Values.config.log_level }}"
USD_LEDGER_ID: "{{ .Values.config.usd_ledger_id }}"
NOOP_EQUITY_ACCOUNT_ID: "{{ .Values.config.noop_equity_account_id }}"
GOOGLE_OUATH2_CLIENT_ID: "{{ .Values.config.google_oauth2_client_id }}"
TEMPORAL_URL: "{{ .Values.config.temporal.url }}"
TWILIO_ACCOUNT_SID: "{{ .Values.config.twilio.account_sid }}"
TWILIO_SERVICE_SID: "{{ .Values.config.twilio.service_sid }}"
ZENDESK_USER: "{{ .Values.config.zenddesk.user }}"
OTEL_EXPORTER_OTLP_ENDPOINT: "{{ .Values.config.otel.exporter_otlp_endpoint }}"
OTEL_EXPORTER_OTLP_HEADERS: "{{ .Values.config.otel.exporter_otlp_headers }}"
OTEL_SERVICE_NAME: "{{ .Values.config.otel.service_name }}"
ADMIN_POLICY_AUD: "{{ .Values.config.admin.policy_aud }}"
ADMIN_TEAM_DOMAIN: "{{ .Values.config.admin.team_domain }}"
AUTHORISATION_PORT: "{{ .Values.config.authorisation_port }}"
OPEN_PAYMENTS_PORT: "{{ .Values.config.open_payments_port }}"
VAULT_ADDR: "{{ .Values.config.vault.url }}"
VAULT_TRANSIT_ENGINE_PATH: "{{ .Values.config.vault.transit_engine_path }}"
TWITTER_REDIRECT_URL: "{{ .Values.config.twitter.redirect_url }}"
TWITTER_CLIENT_ID: "{{ .Values.config.twitter.client_id }}"
DISCORD_REDIRECT_URL: "{{ .Values.config.discord.redirect_url }}"
ASTRA_CODE_EXCHANGE_REDIRECT: "{{ .Values.config.astra.code_exchange_redirect }}"
RAFIKI_BACKEND_GRAPHQL_URL: "{{ .Values.config.rafiki.graphql.backend_url }}"
RAFIKI_AUTH_GRAPHQL_URL: "{{ .Values.config.rafiki.graphql.auth_url }}"