DB_URL_WITH_CERTS: "{{ print "postgres://" .Values.database.backend.username ":" .Values.database.backend.password "@" .Values.database.host ":" .Values.database.port "/" .Values.database.backend.dbname "?sslmode=disable" | b64enc }}"
DB_URL: "{{ print "postgres://" .Values.database.backend.username ":" .Values.database.backend.password "@" .Values.database.host ":" .Values.database.port "/" .Values.database.backend.dbname "?sslmode=disable" | b64enc }}"

PACIOLI_DB_URL_WITH_CERTS: "{{ print "postgres://" .Values.database.pacioli.username ":" .Values.database.pacioli.password "@" .Values.database.host ":" .Values.database.port "/" .Values.database.pacioli.dbname "?sslmode=disable" | b64enc }}"
PACIOLI_DB_URL: "{{ print "postgres://" .Values.database.pacioli.username ":" .Values.database.pacioli.password "@" .Values.database.host ":" .Values.database.port "/" .Values.database.pacioli.dbname "?sslmode=disable" | b64enc }}"

TWILIO_ACCOUNT_TOKEN: "{{ .Values.config.twilio.account_token | b64enc }}"
ZENDESK_TOKEN: "{{ .Values.config.zenddesk.token | b64enc }}"
SENDGRID_API_KEY: "{{ .Values.config.sendgrid.api_key | b64enc }}"
SMARTY_AUTH_ID: "{{ .Values.config.smarty.auth_id | b64enc }}"
SMARTY_AUTH_TOKEN: "{{ .Values.config.smarty.auth_token | b64enc }}"
PUSHER_ADDR: "{{ .Values.config.pusher.addr | b64enc }}"
SEGMENT_KEY: "{{ .Values.config.segment.key | b64enc }}"
PERSONA_TOKEN: "{{ .Values.config.persona.token | b64enc }}"
PERSONA_WEBHOOK_TOKEN: "{{ .Values.config.persona.webhook_token | b64enc }}"
SLACK_TOKEN: "{{ .Values.config.slack.token | b64enc }}"
TWITTER_CLIENT_SECRET: "{{ .Values.config.twitter.client_secret | b64enc }}"
CDN_KEY: "{{ .Values.config.cdn.key | b64enc }}"
BASISTHEORY_API_KEY: "{{ .Values.config.basis_theory.api_key | b64enc }}"
BT_TOKEN: "{{ .Values.config.basis_theory.token | b64enc }}"
TWITTER_BEARER_TOKEN: "{{ .Values.config.twitter.bearer_token | b64enc }}"
SENTRY_DSN: "{{ .Values.config.sentry.dsn | b64enc }}"
DISCORD_CLIENT_SECRET: "{{ .Values.config.discord.redirect_url | b64enc }}"
DISCORD_CLIENT_ID: "{{ .Values.config.discord.redirect_url | b64enc }}"
SLACK_CLIENT_ID: "{{ .Values.config.slack.token | b64enc }}"
SLACK_CLIENT_SECRET: "{{ .Values.config.slack.token | b64enc }}"
SLACK_SIGNING_SECRET: "{{ .Values.config.slack.token | b64enc }}"
XAGO_API_SECRET: "{{ .Values.config.xago.api_secret | b64enc }}"
XAGO_API_PUBLIC_KEY: "{{ .Values.config.xago.api_public_key | b64enc }}"
ASTRA_WEBHOOK_BEARER_TOKEN: "{{ .Values.config.astra.webhook_bearer_token | b64enc }}"
ASTRA_CLIENT_ID: "{{ .Values.config.astra.client_id | b64enc }}"
ASTRA_CLIENT_SECRET: "{{ .Values.config.astra.client_secret | b64enc }}"
PTI_JWK: "{{ .Values.config.pti.jwk | b64enc }}"
PTI_CLIENT_ID: "{{ .Values.config.pti.client_id | b64enc }}"
GATEHUB_APP_ID: "{{ .Values.config.gatehub.app_id | b64enc }}"
GATEHUB_SECRET: "{{ .Values.config.gatehub.secret | b64enc }}"
GATEHUB_WEBHOOK_SECRET: "{{ .Values.config.gatehub.secret | b64enc }}"
CHIMONEY_WEBHOOK_SECRET: "{{ .Values.config.chimoney.webhook_secret | b64enc }}"
CHIMONEY_TOKEN: "{{ .Values.config.chimoney.token | b64enc }}"
DATO_API_TOKEN: "{{ .Values.config.dato.api_token | b64enc }}"