apiVersion: v2
name: rafiki-boutique-backend
description: A Helm chart for Kubernetes

type: application
version: 0.1.8
appVersion: "v0.1.53"

dependencies:
  - name: common
    version: 0.1.0
    repository: file://../../common

maintainers:
  - name: golobitch
    email: tadej.golobic@gatehub.net
