apiVersion: v2
name: rafiki-boutique-backend
description: A Helm chart for Kubernetes

type: application
version: 0.1.11
appVersion: "v0.1.65"

dependencies:
  - name: common
    version: 0.6.1
    repository: https://interledger.github.io/charts/interledger

maintainers:
  - name: golobitch
    email: tadej.golobic@gatehub.net
  - name: beniaminmunteanu
    email: beniamin@interledger.foundation
