apiVersion: v2
name: jopacc-idp
description: IDP Frontend Helm chart for Kubernetes

type: application
version: 0.0.2
appVersion: "v0.0.2"

dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common

maintainers:
  - name: beniamin
    email: beniamin@interledger.foundation
