BOUTIQUE_BACKEND_PORT: "{{ .Values.port }}"
BOUTIQUE_BACKEND_FRONTEND_URL: "{{ .Values.frontendUrl }}"
BOUTIQUE_BACKEND_KEY_ID: "{{ .Values.keyId }}"
BOUTIQUE_BACKEND_PAYMENT_POINTER: "{{ .Values.paymentPointer }}"