{{- include "common.secret" (list . "jopacc-rafiki-middleware-docker-secret") }}

{{- define "jopacc-rafiki-middleware-docker-secret" -}}
{{- $top := first . }}
type: kubernetes.io/dockerconfigjson
metadata:
    name: ghrc-image-pull-secret
data:
  .dockerconfigjson: "eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJZbVZ1YVdGdGFXNXRkVzUwWldGdWRUcG5hSEJmWjA5VFpEazFOREJNYXpCa2NEUnZaVEZFVTNvMmMxUTFRalpCZWxRNU1sRjZNR1l4In19fQ=="
{{- end }}
