apiVersion: v2
name: web-monetization-tools-backend
description: A Helm chart for Kubernetes

type: application
version: 0.0.8
appVersion: "v0.0.8"

dependencies:
  - name: common
    version: 0.6.1
    repository: https://interledger.github.io/charts/interledger

maintainers:
  - name: golobitch
    email: tadej.golobic@gatehub.net
