{{- define "web-monetization-tools.frontend.SecretsMap" -}}
{{- end }}
{{- if .Values.config.frontend.shouldCreateSecrets }}
{{- include "common.secretMapper" (list . .Values.secretsMaps.frontend "web-monetization-tools.frontend.SecretsMap") }}
{{- end }}
