{{- define "rafiki.frontend.ConfigMap" -}}
{{- end }}
{{- if .Values.deployments.frontend.enabled }}
{{- include "common.configMapper" (list . .Values.configMaps.frontend "rafiki.frontend.ConfigMap") }}
{{- end }}
