{{- define "rafiki.backend.ConfigMap" -}}
{{- end }}
{{- if .Values.deployments.backend.enabled }}
{{- include "common.configMapper" (list . .Values.configMaps.backend "rafiki.backend.ConfigMap") }}
{{- end }}
