{{- define "rafiki.frontend.service" -}}
{{- end }}
{{- if .Values.deployments.frontend.enabled }}
{{- include "common.svc" (list . .Values.services.frontend .Values.deployments.frontend "rafiki.frontend.service") }}
{{- end }}