apiVersion: v2
name: rafiki-boutique
description: Rafiki Boutique Helm chart for Kubernetes
home: https://github.com/interledger/testnet

type: application
version: 0.2.7
appVersion: "v0.1.67"

dependencies:
  - name: common
    version: 0.9.0
    repository: https://interledger.github.io/charts/interledger

maintainers:
  - name: golobitch
    email: tadej.golobic@gatehub.net
  - name: beniaminmunteanu
    email: beniamin@interledger.foundation
