apiVersion: v2
name: rafiki-auth
description: Rafiki Auth Helm chart for Kubernetes
home: https://github.com/interledger/rafiki

type: application
version: 0.8.0
appVersion: "v1.1.1-beta"

dependencies:
  - name: common
    version: 0.2.0
    repository: https://interledger.github.io/charts/interledger

    # import-values:
    #   - child: securityContext
    #     parent: securityContext
    #   - child: podSecurityContext
    #     parent: podSecurityContext

maintainers:
  - name: golobitch
    email: tadej.golobic@gatehub.net
  - name: Stephan Butler
    email: stephan@interledger.foundation
