apiVersion: v2
name: rafiki-auth
description: Rafiki Auth Helm chart for Kubernetes
home: https://github.com/interledger/rafiki

type: application
version: 0.5.3
appVersion: "v1.0.0-alpha.20"

dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common

maintainers:
  - name: golobitch
    email: tadej.golobic@gatehub.net
