# This example shows the fields typically configured when setting up a
# Rafiki Auth instance.

secrets:
  create: true

databaseUri:
  value: "postgresql://rafiki-backend-postgresql:5432/rafiki-backend"

redisUri:
  value: "redis://rafiki-auth-redis-master:6379"

identityServer:
  domain: https://walet.interledger-test.dev/grant-interactions
  serverSecret:
    value: "changeme"

authServerUrl: "https://auth.interledger-test.dev"

ingress:
  enabled: true
  className: nginx
  # tls:
  #  - secretName: interledger-test-dev-tls
  #    hosts:
  #      - auth.interledger-test.dev
  hosts:
    - host: auth.interledger-test.dev
      paths:
        - path: /
          pathType: Prefix
          service:
            name: rafiki-auth-service
            port: 3006


cookieKey:
  value: "changeme"
