apiVersion: v2
name: rafiki-money-frontend
description: Rafiki Money Frontend Helm chart for Kubernetes
home: https://github.com/interledger/testnet

type: application
version: 0.0.40
appVersion: "v0.1.58"

dependencies:
  - name: common
    version: 0.1.0
    repository: https://interledger.github.io/charts/interledger

maintainers:
  - name: golobitch
    email: tadej.golobic@gatehub.net
  - name: beniaminmunteanu
    email: beniamin@interledger.foundation
