{{- define "app.SecretsMap" -}}
{{- end }}
{{- if and .Values.deployments.app.enabled .Values.config.shouldCreateSecrets }}
{{- include "common.secretMapper" (list . .Values.secretMaps "app.SecretsMap") }}
{{- end }}
