apiVersion: v2
name: rafiki
description: Rafiki Helm chart for Kubernetes
home: https://github.com/interledger/rafiki

type: application
version: 0.1.0
appVersion: "v1.2.0-beta"

dependencies:
  - name: common
    version: 0.5.1
    # repository: https://interledger.github.io/charts/interledger
    repository: file://../common        

maintainers:
  - name: Stephan Butler
    email: stephan@interledger.foundation
