apiVersion: v2
name: rafiki
description: Rafiki Helm chart for Kubernetes
home: https://github.com/interledger/rafiki

type: application
version: 0.2.7
appVersion: "v1.2.0-beta"

dependencies:
  - name: common
    version: 0.6.1
    repository: https://interledger.github.io/charts/interledger

maintainers:
  - name: Stephan Butler
    email: stephan@interledger.foundation
