apiVersion: v2
name: jopacc-rafiki-middleware-backend
description: A Helm chart for Kubernetes

type: application
version: 0.0.1
appVersion: "v0.0.1"

dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common
    import-values:
       - child: securityContext
         parent: securityContext
       - child: podSecurityContext
         parent: podSecurityContext
  - name: postgresql
    version: '15.5.27'
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: '19.0.1'
    repository: https://charts.bitnami.com/bitnami
