apiVersion: v2
name: jopacc-rafiki-middleware-backend
description: A Helm chart for Kubernetes

type: application
version: 0.0.5
appVersion: "v0.0.2"

dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common
    import-values:
       - child: securityContext
         parent: securityContext
       - child: podSecurityContext
         parent: podSecurityContext


maintainers:
  - name: beniamin
    email: beniamin@interledger.foundation
