{{- define "interledger-cards.backend.SecretsMap" -}}
{{- end }}
{{- if .Values.config.backend.shouldCreateSecrets }}
{{- include "common.secretMapper" (list . .Values.secretsMaps.backend "interledger-cards.backend.SecretsMap") }}
{{- end }}
