{{- include "common.secret" (list . "cards.secret") }}
{{- define "cards.secret" -}}
{{- $top := first . }}
data:
  {{- range $top.Values.secrets }}
    {{- tpl ($top.Files.Get .) $top | nindent 6 -}}
  {{- end }}
{{- end }}
