apiVersion: v2
name: testnet-wallet
description: TestNet Wallet Helm chart for Kubernetes
home: https://github.com/interledger/testnet

type: application
version: 0.2.4
appVersion: "v0.1.66"

dependencies:
  - name: common
    version: 0.6.1
    repository: https://interledger.github.io/charts/interledger

maintainers:
  - name: golobitch
    email: tadej.golobic@gatehub.net
  - name: beniaminmunteanu
    email: beniamin@interledger.foundation
