LOG_LEVEL: "{{ .Values.logLevel }}"
ADMIN_PORT: "{{ .Values.port.admin }}"
CONNECTOR_PORT: "{{ .Values.port.connector }}"
OPEN_PAYMENTS_PORT: "{{ .Values.port.openPayments }}"
USE_TIGERBEETLE: "{{ .Values.useTigerBeetle }}"
NONCE_REDIS_KEY: "{{ .Values.redis.nonce }}"
AUTH_SERVER_GRANT_URL: "{{ .Values.auth.grantUrl }}"
AUTH_SERVER_INTROSPECTION_URL: "{{ .Values.auth.introspectionUrl }}"
ILP_ADDRESS: "{{ .Values.ilp.address }}"
ADMIN_KEY: "{{ .Values.adminKey }}"
PUBLIC_HOST: "{{ .Values.ilp.host }}"
OPEN_PAYMENTS_URL: "{{ .Values.ilp.host }}"
WALLET_ADDRESS_URL: "{{ .Values.ilp.host }}/.well-known/pay"
WEBHOOK_URL: "{{ .Values.webhook.url }}"
WEBHOOK_TIMEOUT: "{{ .Values.webhook.timeout }}"
EXCHANGE_RATES_URL: "{{ .Values.rates.url }}"
QUOTE_URL: "{{ .Values.quote.url }}"
ILP_CONNECTOR_URL: "{{ .Values.ilp.connector }}"
SLIPPAGE: "{{ .Values.slippage }}"
INSTANCE_NAME: "{{ .Values.instanceName }}"
ENABLE_TELEMETRY: "{{ .Values.telemetry.enabled }}"
LIVENET: "{{ .Values.livenet }}"
KEY_ID: "{{ .Values.keyId }}"
TRUST_PROXY: "{{ .Values.trustProxy }}"
