LOG_LEVEL: "{{ required "values.logLevel must be set" .Values.logLevel }}"
ADMIN_PORT: "{{ required "port.admin must be set" .Values.port.admin }}"
CONNECTOR_PORT: "{{ required "port.connector must be set" .Values.port.connector }}"
OPEN_PAYMENTS_PORT: "{{ required "port.openPayments must be set" .Values.port.openPayments }}"
USE_TIGERBEETLE: "{{ required "useTigerbeetle must be set" .Values.useTigerbeetle }}"
NONCE_REDIS_KEY: "{{ .Values.redis.nonce }}"
AUTH_SERVER_GRANT_URL: "{{ required "auth.grantUrl must be set" .Values.auth.grantUrl }}"
AUTH_SERVER_INTROSPECTION_URL: "{{ required "auth.introspectionUrl must be set" .Values.auth.introspectionUrl }}"
ILP_ADDRESS: "{{ required "ilp.address must be set" .Values.ilp.address }}"
PUBLIC_HOST: "{{ required "ilp.host must be set" .Values.ilp.host }}"
OPEN_PAYMENTS_URL: "{{ required "ilp.host must be set" .Values.ilp.host }}"
WALLET_ADDRESS_URL: "{{ required "ilp.host must be set" .Values.ilp.host }}/.well-known/pay"
WEBHOOK_URL: "{{ required "webhook.url must be set" .Values.webhook.url }}"
WEBHOOK_TIMEOUT: "{{ required "webhook.timeout must be set" .Values.webhook.timeout }}"
EXCHANGE_RATES_URL: "{{ required "rates.url must be set" .Values.rates.url }}"
ILP_CONNECTOR_URL: "{{ required "ilp.connector must be set" .Values.ilp.connector }}"
SLIPPAGE: "{{ required "slippage must be set" .Values.slippage }}"
INSTANCE_NAME: "{{ required "instanceName must be set" .Values.instanceName }}"
ENABLE_TELEMETRY: "{{ required "telemetry.enabled must be set" .Values.telemetry.enabled }}"
KEY_ID: "{{ required "key.id must be set" .Values.key.id }}"
TRUST_PROXY: "{{ required "trustProxy must be set" .Values.trustProxy }}"
WALLET_ADDRESS_REDIRECT_HTML_PAGE: "{{ .Values.walletAddressRedirectHtmlPage }}"
NODE_ENV: "{{ required "nodeEnv must be set" .Values.nodeEnv }}"
PRIVATE_KEY_FILE: "/mnt/keys/private-key-file"