DATABASE_URL: {{ .Values.databaseUrl.value | b64enc | quote }}
REDIS_URL: {{ .Values.redisUrl.value | b64enc | quote }}
SIGNATURE_SECRET: {{ .Values.quoteSignatureSecret.value | b64enc | quote }}
STREAM_SECRET: {{ .Values.ilp.streamSecret.value | b64enc | quote }}