DATABASE_URL: {{ .Values.databaseUri.value | b64enc | quote }}
REDIS_URL: {{ .Values.redisUri.value | b64enc | quote }}
SIGNATURE_SECRET: {{ .Values.quoteSignatureSecret.value | b64enc | quote }}
STREAM_SECRET: {{ .Values.ilp.streamSecret.value | b64enc | quote }}