{{- define "backend.deployment" -}}
{{- $top := first . }}
{{- if $top.Values.backend.enabled }}
{{- $cfgObj := include "common.configMapper" (list $top $top.Values.configMaps.backend) | fromYaml -}}
{{- $dataHash := $cfgObj.data | toJson | sha256sum -}}
spec:
  template:
    metadata:
      annotations:
        ilf-configmap-backend-sha256: {{ $dataHash | quote }}
{{- end }}
{{- end }}
{{- include "common.deployment" (list . .Values.backend .Values.backend.autoscaling .Values.backend.serviceAccount "backend.deployment") }}
