{{- define "admin.deployment" -}}
{{- $top := first . }}
{{- if $top.Values.admin.enabled }}
{{- $cfgObj := include "common.configMapper" (list $top $top.Values.configMaps.admin) | fromYaml -}}
{{- $dataHash := $cfgObj.data | toJson | sha256sum -}}
spec:
  template:
    metadata:
      annotations:
        ilf-configmap-admin-sha256: {{ $dataHash | quote }}
{{- end }}
{{- end }}
{{- include "common.deployment" (list . .Values.admin .Values.admin.autoscaling .Values.admin.serviceAccount "admin.deployment") }}
