{{- define "app.SecretsMap" -}}
{{- end }}
{{- if and .Values.backend.enabled .Values.config.shouldCreateSecrets }}
{{- include "common.secretMapper" (list . .Values.secretsMaps.backend "app.SecretsMap") }}
{{- end }}
