apiVersion: v2
name: rafiki-frontend
description: Rafiki Frontend Helm chart for Kubernetes
home: https://github.com/interledger/rafiki

type: application
version: 0.5.2
appVersion: "v1.0.0-alpha.19"

dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common

maintainers:
  - name: golobitch
    email: tadej.golobic@gatehub.net
