apiVersion: v2
name: interledger-cards
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "v0.0.3"

dependencies:
  - name: common
    version: 0.6.1
    repository: https://interledger.github.io/charts/interledger

maintainers:
  - name: golobitch
    email: tadej@interledger.org
  - name: Stephan Butler
    email: stephan@interledger.foundation

