GRAPHQL_URL: "{{ .Values.serviceUrls.GRAPHQL_URL}}"
LOG_LEVEL: "{{ .Values.logLevel }}"
NODE_ENV: "{{ .Values.nodeEnv }}"
PORT: "{{ .Values.port }}"
AUTH_ENABLED: "{{ .Values.kratos.enabled }}"
OPEN_PAYMENTS_URL: "{{ .Values.serviceUrls.OPEN_PAYMENTS_URL }}"