{{- include "common.ingress" (list . .Values.ingress "rafiki-money-backend.ingress") }}

 {{- define "rafiki-money-backend.ingress" -}}
 metadata:
     annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
        nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
        nginx.ingress.kubernetes.io/websocket-services: "wallet-backend-service"
 {{- end }}