{{- define "rafiki-cards.backend.SecretsMap" -}}
{{- end }}
{{- if .Values.config.shouldCreateSecrets }}
{{- include "common.secretMapper" (list . .Values.secretsMaps.backend "rafiki-cards.backend.SecretsMap") }}
{{- end }}
