{{- define "temporal.secret" -}}
{{- $top := first . }}
data:
  {{- range $top.Values.secrets.temporal }}
    {{- tpl ($top.Files.Get .) $top | nindent 2 -}}
  {{- end }}
{{- end }}
{{- include "common.secret" (list . "temporal.secret") }}