apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ui
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-ui
    app.kubernetes.io/instance: {{ .Release.Name }}-ui
spec:
  type: ClusterIP
  ports:
    - name: frontend
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-ui
    app.kubernetes.io/instance: {{ .Release.Name }}-ui