{{- include "common.secret" (list . "jopacc-rafiki-middleware-backend.secret") }}
{{- define "jopacc-rafiki-middleware-backend.secret" -}}
{{- $top := first . }}
data:
  {{- range $top.Values.secrets }}
    {{- tpl ($top.Files.Get .) $top | nindent 6 -}}
  {{- end }}
{{- end }}
