NODE_ENV: "{{ .Values.nodeEnv }}"
PORT: "{{ .Values.port }}"
COOKIE_NAME: "{{ .Values.cookie.name }}"
COOKIE_TTL: "{{ .Values.cookie.ttl }}"
OPEN_PAYMENTS_HOST: "{{ .Values.hosts.openPayments }}"
GRAPHQL_ENDPOINT: "{{ .Values.hosts.graphqlEndpoint }}"
AUTH_GRAPHQL_ENDPOINT: "{{ .Values.hosts.authGraphqlEndpoint }}"
RAFIKI_MONEY_FRONTEND_HOST: "{{ .Values.hosts.frontend }}"
AUTH_DOMAIN: "{{ .Values.hosts.auth }}"
SEND_EMAIL: "{{ .Values.email.send }}"
FROM_EMAIL: "{{ .Values.email.from }}"
AUTH_INTERACTION_COOKIE_SAME_SITE: "{{ .Values.interaction.cookieSameSite }}"
GATEHUB_ENV: "{{ .Values.gatehub.env }}"
GATEHUB_ACCESS_KEY: "{{ .Values.gatehub.accessKey }}"
GATEHUB_GATEWAY_UUID: "{{ .Values.gatehub.gatewayUuid }}"
GATEHUB_VAULT_UUID_EUR: "{{ .Values.gatehub.vault.eur }}"
GATEHUB_VAULT_UUID_USD: "{{ .Values.gatehub.vault.usd }}"
GATEHUB_ORG_ID: "{{ .Values.gatehub.organizationId }}"
GATEHUB_SETTLEMENT_WALLET_ADDRESS: "{{ .Values.gatehub.settlementWalletAddress }}"
GATEHUB_CARD_APP_ID: "{{ .Values.gatehub.cards.appId }}"
GATEHUB_ACCOUNT_PRODUCT_CODE: "{{ .Values.gatehub.cards.accountProductCode }}"
GATEHUB_CARD_PRODUCT_CODE: "{{ .Values.gatehub.cards.productCode }}"
GATEHUB_NAME_ON_CARD: "{{ .Values.gatehub.cards.nameOnCard }}"
GATEHUB_CARD_PP_PREFIX: "{{ .Values.gatehub.cards.paymentPointerPrefix }}"
PAYMENT_POINTER: "{{ .Values.paymentPointer }}"
CARD_PIN_HREF: "{{ .Values.card.pinUrl }}"
CARD_DATA_HREF: "{{ .Values.card.dataUrl }}"
