
DATABASE_URL: "{{ .Values.database.url | b64enc }}"
COOKIE_PASSWORD: "{{ .Values.cookie.password | b64enc }}"
AUTH_IDENTITY_SERVER_SECRET: "{{ .Values.identity.serverSecret | b64enc }}"
REDIS_URL: "{{ .Values.redis.url | b64enc }}"
RAFIKI_WEBHOOK_SIGNATURE_SECRET: "{{ .Values.webhook.signatureSecret | b64enc }}"
GATEHUB_SECRET_KEY: "{{ .Values.gatehub.secretKey | b64enc }}"
GATEHUB_WEBHOOK_SECRET: "{{ .Values.gatehub.webhookSecret | b64enc}}"
SENDGRID_API_KEY: "{{ .Values.email.sendgridKey | b64enc }}"
RATE_API_KEY: "{{ .Values.rate.apiKey | b64enc }}"
STRIPE_WEBHOOK_SECRET: "{{ .Values.stripe.webhookSecret | b64enc }}"
STRIPE_SECRET_KEY: "{{ .Values.stripe.secretKey | b64enc }}"
