apiVersion: v2
name: rafiki-boutique-frontend-jopacc
description: A Helm chart for Kubernetes

type: application
version: 0.1.10
appVersion: "v0.1.51"

dependencies:
  - name: common
    version: 0.1.0
    repository: file://../../common

maintainers:
  - name: golobitch
    email: tadej.golobic@gatehub.net
