{{- define "web-monetization-tools.backend.SecretsMap" -}}
{{- end }}
{{- if .Values.config.backend.shouldCreateSecrets }}
{{- include "common.secretMapper" (list . .Values.secretsMaps.backend "web-monetization-tools.backend.SecretsMap") }}
{{- end }}
