apiVersion: v2
name: ilf-wallet-hello
description: Meta chart repository for deploying ingress and internal reverse proxy if needed
home: https://github.com/interledger/interledger-app

type: application
version: 0.1.1
appVersion: "v0.1.0"

dependencies:
  - name: common
    version: 0.2.0
    repository: file://../../common

maintainers:
  - name: Stephan Butler
    email: stephan@interledger.foundation
