apiVersion: v2
name: ilf-wallet-entrypoint
description: Meta chart repository for managing cluster entrypoints
home: https://github.com/interledger/interledger-app

type: application
version: 1.0.1
appVersion: "v1.0.1"

dependencies:
  - name: common
    version: 0.3.2
    repository: https://interledger.github.io/charts/interledger

maintainers:
  - name: Stephan Butler
    email: stephan@interledger.foundation
