ACCESS_TOKEN_DELETION_DAYS: "{{ required "accessToken.deletionDays must be set" .Values.accessToken.deletionDays }}"
ACCESS_TOKEN_EXPIRY_SECONDS: "{{ required "accessToken.expirySeconds must be set" .Values.accessToken.expirySeconds }}"
ADMIN_PORT: "{{ required "port.admin must be set" .Values.port.admin }}"
AUTH_PORT: "{{ required "port.auth must be set" .Values.port.auth }}"
AUTH_SERVER_URL: "{{ required "authServerUrl must be set" .Values.authServerUrl }}"
DATABASE_CLEANUP_WORKERS: "{{ required "workers.cleanup must be set" .Values.workers.cleanup }}"
IDENTITY_SERVER_URL: "{{ required "identityServer.domain must be set" .Values.identityServer.domain }}"
INCOMING_PAYMENT_INTERACTION: "{{ required "interaction.incomingPayment must be set" .Values.interaction.incomingPayment }}"
QUOTE_INTERACTION: "{{ required "interaction.quote must be set" .Values.interaction.quote }}"
INTROSPECTION_PORT: "{{ required "port.introspection must be set" .Values.port.introspection }}"
LOG_LEVEL: "{{ required "logLevel must be set" .Values.logLevel }}"
NODE_ENV: "{{ required "nodeEnv must be set" .Values.nodeEnv }}"
PORT: "{{ required "port.auth must be set" .Values.port.auth }}"
WAIT_SECONDS: "{{ required "grant.waitSeconds must be set" .Values.grant.waitSeconds }}"
TRUST_PROXY: "{{ required "trustProxy must be set" .Values.trustProxy }}"
INTERACTION_COOKIE_SAME_SITE: "{{ required "interaction.cookieSameSite must be set" .Values.interaction.cookieSameSite }}"
