{{- define "rafiki.backend.SecretsMap" -}}
{{- end }}
{{- if and .Values.deployments.backend.enabled .Values.config.backend.shouldCreateSecrets }}
{{- include "common.secretMapper" (list . .Values.secretsMaps.backend "rafiki.backend.SecretsMap") }}
{{- end }}
