apiVersion: v2
name: ilf-wallet-frontend
description: Interledger App Wallet backend service for the Interledger App network
home: https://github.com/interledger/interledger-app

type: application
version: 0.2.6
appVersion: "v0.2.2"

dependencies:
  - name: common
    version: 0.4.2
    repository: https://interledger.github.io/charts/interledger

maintainers:
  - name: Stephan Butler
    email: stephan@interledger.foundation
