#
# Chart for the Interledger App Wallet Frontend called Protea.
#

imageOverride:
  repository: europe-west4-docker.pkg.dev/wallet-451208/interledger-app
  name: protea
  tag: v1.1.0

config:
  backend:
    grpc:
      url: "http://wallet-backend-service:8443"

  redis:
    url_ref: redisURL

  # Note that in the secret this should be a string. The string itself should
  # be a json array of strings.
  cookie_secrets_ref: cookieSecretsArrStr

  otel:
    endpoint: grpc://api.honeycomb.io:443
    headers_ref: otelExporterHeaders
    service_name: protea

  pusher:
    app_key_ref: pusherAppKey
    app_cluster_ref: pusherAppCluster
  
  gate_signup: false
  kratos_url: http://kratos-public
  payment_pointer_base: sandbox.ilp.link

  bt_token_ref: basisTheoryToken

  sentry_dsn_ref: sentryDSN

  segment_api_key_ref: segmentAPIKey

  rafiki:
    auth:
      endpoint: http://rafiki-auth:3003/graphql
      secret_ref: rafikiAuthSecret

  
  cf_turnstile_site_key_ref: "turnstileSiteKey"
  cf_turnstile_secret_key_ref: "turnstileSecret"

  environment: dev

replicaCount: 2
nodeSelector: {}

service:
  - name: service
    type: ClusterIP
    ports:
      - port: 3000
        targetPort: 3000
        protocol: TCP
        name: http

configmap:
  - files/config.yaml


containers:
  # Frontend
  - name: frontend
    imagePullPolicy: Always
    livenessProbe:
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 3      
      httpGet:
        path: /healthz
        port: 3000
    readinessProbe:
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 3      
      httpGet:
        path: /healthz
        port: 3000
    envFrom:
      - configMapRef:
          name: '{{ include "common.fullname" . }}'
    env:
      - name: COOKIE_SECRETS
        valueFrom:
            secretKeyRef:
              name: '{{ include "common.fullname" . }}'
              key: '{{ .Values.config.cookie_secrets_ref }}'
      - name: PUSHER_APP_KEY
        valueFrom:
            secretKeyRef:
              name: '{{ include "common.fullname" . }}'
              key: '{{ .Values.config.pusher.app_key_ref }}'
      - name: PUSHER_APP_CLUSTER
        valueFrom:
            secretKeyRef:
              name: '{{ include "common.fullname" . }}'
              key: '{{ .Values.config.pusher.app_cluster_ref }}'
      - name: BT_TOKEN
        valueFrom:
            secretKeyRef:
              name: '{{ include "common.fullname" . }}'
              key: '{{ .Values.config.bt_token_ref }}'
      - name: SENTRY_DSN
        valueFrom:
            secretKeyRef:
              name: '{{ include "common.fullname" . }}'
              key: '{{ .Values.config.sentry_dsn_ref }}'
      - name: SEGMENT_API_KEY
        valueFrom:
            secretKeyRef:
              name: '{{ include "common.fullname" . }}'
              key: '{{ .Values.config.segment_api_key_ref }}'
      - name: RAFIKI_AUTH_SECRET
        valueFrom:
            secretKeyRef:
              name: '{{ include "common.fullname" . }}'
              key: '{{ .Values.config.rafiki.auth.secret_ref }}'
      - name: CF_TURNSTILE_SITE_KEY
        valueFrom:
            secretKeyRef:
              name: '{{ include "common.fullname" . }}'
              key: '{{ .Values.config.cf_turnstile_site_key_ref }}'
      - name: CF_TURNSTILE_SECRET_KEY
        valueFrom:
            secretKeyRef:
              name: '{{ include "common.fullname" . }}'
              key: '{{ .Values.config.cf_turnstile_secret_key_ref }}'
      - name: REDIS_URL
        valueFrom:
            secretKeyRef:
              name: '{{ include "common.fullname" . }}'
              key: '{{ .Values.config.redis.url_ref }}'
    ports:
      - name: http
        containerPort: 3000
    resources:
      requests:
        memory: 256Mi
        cpu: 80m
      limits:
        memory: 1024Mi
        cpu: 1000m
