#
# Chart for the Interledger App Wallet Frontend called Protea.
#

config:
  backend:
    grpc:
      url: "http://wallet-backend-service:8443"

  redis:
    url_ref: redis-url

  # Note that in the secret this should be a string. The string itself should
  # be a json array of strings.
  cookie_secrets_ref: cookie-secrets

  otel:
    endpoint: grpc://api.honeycomb.io:443
    headers: x-honeycomb-team=xxxxxxxxxxxxx
    service_name: protea

  pusher:
    app_key_ref: pusher-app-key
    app_cluster_ref: pusher-app-cluster
  
  gate_signup: false
  kratos_url: http://kratos-public
  payment_pointer_base: sandbox.ilp.link

  bt_token_ref: bt-token

  sentry_dsn_ref: sentry-dsn

  segment_api_key_ref: segment-api-key

  rafiki:
    auth:
      endpoint: http://rafiki-auth:3003/graphql
      secret_ref: rafiki-auth-secret

  
  cf_turnstile_site_key_ref: "turnstile-site-key"
  cf_turnstile_secret_key_ref: "turnstile-secret"

  environment: dev

replicaCount: 3
nodeSelector: {}

service:
  - name: service
    type: ClusterIP
    ports:
      - port: 3000
        targetPort: 3000
        protocol: TCP
        name: http

configmap:
  - files/config.yaml

secrets:
  - files/secret.yaml

containers:
  # Frontend
  - name: frontend
    image:
      repository: europe-west4-docker.pkg.dev/wallet-451208/interledger-app
      name: protea
      imagePullPolicy: Always
    livenessProbe:
      httpGet:
        path: /healthz
        port: 3000
    readinessProbe:
      httpGet:
        path: /healthz
        port: 3000
    envFrom:
      - configMapRef:
          name: "{{ .Release.Name }}"
      - secretRef:
          name: COOKIE_SECRETS
          valueFrom:
            secretKeyRef:
              name: '{{ include "common.fullname" . }}'
              key: '{{ .Values.config.cookie_secrets_ref }}'
      - secretRef:
          name: PUSHER_APP_KEY
          valueFrom:
            secretKeyRef:
              name: '{{ include "common.fullname" . }}'
              key: '{{ .Values.config.pusher.app_key_ref }}'
      - secretRef:
          name: PUSHER_APP_CLUSTER
          valueFrom:
            secretKeyRef:
              name: '{{ include "common.fullname" . }}'
              key: '{{ .Values.config.pusher.app_cluster_ref }}'
      - secretRef:
          name: BT_TOKEN
          valueFrom:
            secretKeyRef:
              name: '{{ include "common.fullname" . }}'
              key: '{{ .Values.config.bt_token_ref }}'
      - secretRef:
          name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: '{{ include "common.fullname" . }}'
              key: '{{ .Values.config.sentry_dsn }}'
      - secretRef:
          name: SEGMENT_API_KEY
          valueFrom:
            secretKeyRef:
              name: '{{ include "common.fullname" . }}'
              key: '{{ .Values.config.segment_api_key_ref }}'
      - secretRef:
          name: RAFIKI_AUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: '{{ include "common.fullname" . }}'
              key: '{{ .Values.config.rafiki.auth.secret_ref }}'
      - secretRef:
          name: CF_TURNSTILE_SITE_KEY
          valueFrom:
            secretKeyRef:
              name: '{{ include "common.fullname" . }}'
              key: '{{ .Values.config.cf_turnstile_site_key_ref }}'
      - secretRef:
          name: CF_TURNSTILE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: '{{ include "common.fullname" . }}'
              key: '{{ .Values.config.cf_turnstile_secret_key_ref }}'
      - secretRef:
          name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: '{{ include "common.fullname" . }}'
              key: '{{ .Values.config.redis.url_ref }}'
    ports:
      - name: http
        containerPort: 3000
    resources:
      requests:
        memory: 128Mi
        cpu: 200m
      limits:
        memory: 512Mi
        cpu: 400m
