apiVersion: v2
name: rafiki-backend
description: Rafiki Backend Helm chart for Kubernetes
home: https://github.com/interledger/rafiki

type: application
version: 1.0.2
appVersion: "v1.2.0-beta"

dependencies:
  - name: common
    version: 0.3.4
    repository: https://interledger.github.io/charts/interledger

maintainers:
  - name: golobitch
    email: tadej.golobic@gatehub.net
  - name: Stephan Butler
    email: stephan@interledger.foundation
