{{- define "testnet-wallet-frontend.ingress" -}}
{{- $top := first . -}}
metadata:
  name: {{ include "common.fullname" $top }}-frontend
  annotations:
    {{- if eq $top.Values.ingress.frontend.className "nginx" }}
    nginx.ingress.kubernetes.io/rewrite-target: /
    {{- end }}
{{- end }}

{{- if .Values.ingress.frontend.enabled }}
{{- include "common.ingress" (list . .Values.ingress.frontend "testnet-wallet-frontend.ingress") }}
{{- end }}
