{{- define "testnet-wallet.backend.SecretsMap" -}}
{{- end }}
{{- if .Values.config.backend.shouldCreateSecrets }}
{{- include "common.secretMapper" (list . .Values.secretsMaps.backend "testnet-wallet.backend.SecretsMap") }}
{{- end }}
